# Generated by Django 4.2.5 on 2023-10-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id_aptitude', models.AutoField(db_column='idAptitude', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id_enlace', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id_redes', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('enlace', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stanley',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('nombre_usuario', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('perfil', models.ImageField(blank=True, null=True, upload_to='img')),
                ('password', models.CharField(max_length=128)),
                ('redes_sociales', models.ManyToManyField(to='proyecto.redsocial')),
            ],
        ),
        migrations.CreateModel(
            name='sobremi',
            fields=[
                ('id_sobremi', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_inicio', models.CharField(max_length=1000, null=True)),
                ('descripcion_aptitude', models.CharField(max_length=1000)),
                ('descripcion', models.CharField(max_length=1000)),
                ('aptitudes', models.ForeignKey(db_column='idAptitude', default=None, on_delete=django.db.models.deletion.CASCADE, to='proyecto.aptitude')),
            ],
        ),
        migrations.CreateModel(
            name='portafolio',
            fields=[
                ('id_portafolio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('imagen_portafolio', models.ImageField(blank=True, null=True, upload_to='img')),
                ('descripcion', models.CharField(max_length=210)),
                ('aptitudes', models.ForeignKey(db_column='idAptitude', default=None, on_delete=django.db.models.deletion.CASCADE, to='proyecto.aptitude')),
                ('rutas_enlaces', models.ManyToManyField(to='proyecto.enlace')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('nombre_escuela', models.CharField(max_length=60)),
                ('imagen_certificado', models.ImageField(blank=True, null=True, upload_to='img')),
                ('aptitudes', models.ForeignKey(db_column='idAptitude', default=None, on_delete=django.db.models.deletion.CASCADE, to='proyecto.aptitude')),
                ('enlaces', models.ManyToManyField(to='proyecto.enlace')),
            ],
        ),
    ]
