# Generated by Django 4.2.5 on 2023-10-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stanley',
            name='redes_sociales',
        ),
    ]
