# Generated by Django 4.2.5 on 2023-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_stanley_redes_sociales'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanley',
            name='redes_sociales',
            field=models.ManyToManyField(default=None, to='proyecto.redsocial'),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='id_enlace',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
