# Generated by Django 4.2.5 on 2023-10-08 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_stanley_redes_sociales_alter_enlace_id_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='aptitudes',
            field=models.ForeignKey(db_column='idAptitude', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.aptitude'),
        ),
    ]
