# Generated by Django 4.2.5 on 2023-10-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_certificado_aptitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitude',
            name='id_aptitude',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='aptitudes',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='aptitudes',
        ),
        migrations.RemoveField(
            model_name='sobremi',
            name='aptitudes',
        ),
        migrations.AddField(
            model_name='certificado',
            name='aptitudes',
            field=models.ManyToManyField(default=None, to='proyecto.aptitude'),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='aptitudes',
            field=models.ManyToManyField(default=None, to='proyecto.aptitude'),
        ),
        migrations.AddField(
            model_name='sobremi',
            name='aptitudes',
            field=models.ManyToManyField(default=None, to='proyecto.aptitude'),
        ),
    ]
