# Generated by Django 4.2.5 on 2023-10-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_aptitude_id_aptitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='aptitudes',
            field=models.ManyToManyField(to='proyecto.aptitude'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='aptitudes',
            field=models.ManyToManyField(to='proyecto.aptitude'),
        ),
        migrations.AlterField(
            model_name='sobremi',
            name='aptitudes',
            field=models.ManyToManyField(to='proyecto.aptitude'),
        ),
    ]
