# Generated by Django 4.2.5 on 2023-10-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_certificado_aptitudes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='id_redes',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stanley',
            name='redes_sociales',
            field=models.ManyToManyField(to='proyecto.redsocial'),
        ),
    ]
