# Generated by Django 4.2.5 on 2023-10-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_alter_redsocial_id_redes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='portafolio',
        ),
    ]
