# Generated by Django 4.2.5 on 2023-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_delete_portafolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id_portafolio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('imagen_portafolio', models.ImageField(blank=True, null=True, upload_to='img')),
                ('descripcion', models.CharField(max_length=210)),
                ('aptitudes', models.ManyToManyField(to='proyecto.aptitude')),
                ('rutas_enlaces', models.ManyToManyField(to='proyecto.enlace')),
            ],
        ),
    ]
