# Generated by Django 4.2.7 on 2023-11-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id_aptitude', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(db_column='idEstado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('icono', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sobremi',
            fields=[
                ('id_sobremi', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_inicio', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stanley',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=60)),
                ('perfil', models.ImageField(blank=True, null=True, upload_to='img')),
                ('password', models.CharField(max_length=128)),
                ('redes_sociales', models.ManyToManyField(to='adminStanley.redsocial')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id_portafolio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('imagen_portafolio', models.ImageField(blank=True, null=True, upload_to='img')),
                ('descripcion', models.CharField(max_length=210)),
                ('enlaces_web', models.URLField(blank=True, null=True)),
                ('enlaces_github', models.URLField(blank=True, null=True)),
                ('aptitudes', models.ManyToManyField(to='adminStanley.aptitude')),
                ('id_estado', models.ForeignKey(db_column='idEstado', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminStanley.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('nombre_escuela', models.CharField(max_length=60)),
                ('imagen_certificado', models.ImageField(blank=True, null=True, upload_to='img')),
                ('enlaces_web', models.URLField()),
                ('aptitudes', models.ManyToManyField(to='adminStanley.aptitude')),
            ],
        ),
    ]
