# Generated by Django 5.0 on 2023-12-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminStanley', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanley',
            name='new_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
