# Generated by Django 5.0 on 2023-12-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminStanley', '0002_stanley_new_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stanley',
            name='new_password',
        ),
    ]
