# Generated by Django 5.0 on 2023-12-11 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminStanley', '0003_remove_stanley_new_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='imagen_certificado',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='enlaces_github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='enlaces_web',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='id_estado',
            field=models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.CASCADE, to='adminStanley.estado'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='imagen_portafolio',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='sobremi',
            name='descripcion_inicio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stanley',
            name='perfil',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
