# Generated by Django 5.0 on 2023-12-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminStanley', '0004_alter_certificado_imagen_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='id_estado',
            field=models.ForeignKey(blank=True, db_column='idEstado', on_delete=django.db.models.deletion.CASCADE, to='adminStanley.estado'),
        ),
    ]
